### ISSUE TITLE
gRPC exceptions when reusing the AggregateStore

### ISSUE THREAD

**Issue by ghandmann** [Eventuous/eventuous#60]
Hi,
i recently stumbled upon Eventuous and tried it out a bit. So far i really like it! :)

While hitting my WebAPI Backend with some ApacheBench requests to see how it performs, i noticed that the `AggregateStore` started to bubble up some gRPC exceptions. It recovers after some time, but the exceptions keep comming in a stable-ish frequency (like every 20 Requests or something).

I created a console based reproducer to show the problem. For this i forked your repository and created a new branch [reproducer/grpc-errors-when-reading-aggregates-multiple-times](https://github.com/ghandmann/eventuous/tree/reproducer/grpc-errors-when-reading-aggregates-multiple-times).

The reproducer is using the Booking-Domain from `Eventuous.Sut.Booking` to make sure, that i don't have any bug in my Aggregate-Implementation.

**Comment by alexeyzimarev** [comment]
I've seen the "multiple status headers" error before, not sure what causes it. I am quite sure it's the ESDB gRPC client. Thanks for the repo, I will have a look and, if confirmed, pass it over to ESDB engineering.

**Comment by alexeyzimarev** [comment]
The difference in behaviour you observe is caused by the difference in the way you read the stream using the ESDB client, and how Eventuous uses the client in `EsdbEventStore`. We use the async enumerable returned by the read function, and call the function for each event returned by the enumerable. The original idea was that it would allow us to read unlimitedly long streams without paging. However, it proved to fail, so the paging is now back.

Overall, I find the behaviour of async enumerable returned by the client read contradicting with what an enumerable should do. If I try to read a long stream, it will fail with timeout. It kind of defeats the purpose IMO.

Currently, there's no need to iterate over the async enumerable as we got back to paging. So, we can just enumerate right away and loop through the array.

**Comment by alexeyzimarev** [comment]
Lol, I fixed it. The issue is that we check if the read returns zero, and then exit. It should be checking if the read returns less than the page size. So, we are always reading one more time. It still looks like a bug on ESDB client side, but the issue in Eventuous is gone.

**Comment by alexeyzimarev** [comment]
https://github.com/EventStore/EventStore-Client-Dotnet/issues/173
