### ISSUE TITLE
services.AddShovel to accept transform method injection

### ISSUE THREAD

**Issue by althunibat** [Eventuous/eventuous#61]
passing transform method lacks dependency injection, shovel class may have dependencies to be injected to enrich the transformed events.

**Comment by alexeyzimarev** [comment]
Good point. The issue, as always, is to be able to distinguish between those services, as each shovel (will be called a `Gateway` in the next version) might need a different one. If you look at the current subscription builder and all the stuff related to registrations of subscriptions, you'll see how cumbersome it becomes...

Still, if we agree that the first working solution would be ok assuming only one shovel needs to be there in one application, I can enable registering a shovel without providing a function.

So, instead of:

```csharp
services.AddShovel<AllStreamSubscription, AllStreamSubscriptionOptions, EventStoreProducer>("myShovel", x => {...});
```

You could do this:

```csharp
services.AddSingleton<MyTransformer>();
services.AddSingleton<RouteAndTransform>(sp => sp.GetRequiredService<MyTransformer>.Transform);
services.AddShovel<AllStreamSubscription, AllStreamSubscriptionOptions, EventStoreProducer>("myShovel");
```

That can be done quickly.

**Comment by althunibat** [comment]
we can decide on shovel transform instance upon declaring it, this way it is not one instance which implements RouteAndTransform

```
services.AddSingleton<MyTransformer>();
services
    .AddShovel<AllStreamSubscription, AllStreamSubscriptionOptions, EventStoreProducer>(
        "IntegrationSubscription",
        sp=>sp.GetRequiredService<MyTransformer>.Transform
    );
```

**Comment by alexeyzimarev** [comment]
True, so, basically, for the registration a simple improvement would to accept a function to resolve the transformer.
