### ISSUE TITLE
Validation and event sourcing

### ISSUE THREAD

**Issue by W3Max** [Eventuous/eventuous#67]
Hi @alexeyzimarev,

I really appreciate this project! I have been thinking of giving event sourcing a try for a long time and _eventuous_ seems like the perfect occasion.

With that said, I was wondering about validation and how it works with event sourcing.

For example, in the your demo project (https://github.com/Eventuous/dotnet-sample), there is a delegate function called _IsRoomAvailable_ that you simplified to 
`=> new ValueTask<bool>(true)`

How would you implement the real thing and is it possible to make it transactional, ie, ensuring there is never a room booked twice at the same time?

Thank you!

**Comment by alexeyzimarev** [comment]
I keep telling people that I have my reservations against generic advice where I don't have enough context. Let's take that sample. We discuss it often during workshops, as people as the same question. My response is always "it's not really a technical issue, it's the business issue".

For example, if you build a system for a hotel, guests don't book rooms, they book room types. It's a pool of rooms of the same type (single, double, suite, etc). There, you also need to consider external factors like last-minute cancellations, if you want to have always available rooms if there's an issue (flood, electricity or heating issues) to relocate guests, etc. Remember overbooking policies, which are embedded in the business model. With all this in mind, it doesn't make sense to aim for a 100% guarantee that you don't get overbooked, so you shouldn't waste your time as a developer even trying to solve it technically.

Another thing to remember is to counterweight two factors:
- How likely the constraint is to be violated
- How often it might occur
- What are the consequences of it happening
- Is there a way to mitigate the issue in a different way

For example, if you have a mechanism that detects the policy violation (double booking happened), it's might be easier to handle it by a manual process, which many hotels have. They call the guest, apologies, make some excuses, and offer compensation. It could be possible to relocate the guest to another hotel, upgrade the room, refund with a gift card, etc. Normally, businesses already have guidelines for resolving most of the deviations when they occur, you just need to discover those.

All of that is to explain that most of those "uniqueness" issues are business concerns, not technical.

The Bookings case is probably one of the hardest to solve technically. It's because the room can't have its availability data inside, it's probably even another context. There will be always some delay when the booking propagates to that context and locks the room for some days. If the availability is spread out as one aggregate instance per day (that's how I would model it), there will always be a process involved in updating all those. My aim, therefore, would be to have this delay under control and make sure it is within a given SLA constraint. For example, when a guests books a room, the room availability must be updated within 500 ms because it's unlikely that someone else will try to book the same room at the same time. That I can work with, it's quite different compared to a hard constraint that it has to happen "as a transaction".

Just got a thought that hotels dealing with room pools have more relaxed constraints as there are many rooms in the pool, and they also have much more guests booking at the same time. So, their SLA can be different as it's a different business case. For a small business, the constraint is harder, but the load is also smaller, and the chance of such a deviation to happen is also smaller, so in real life, it's not such an issue. At least, I won't be spending weeks trying to solve it.

**Comment by W3Max** [comment]
@alexeyzimarev  Great explanation! Thank you for taking the time to answer my question! 

On a more technical note, should I use aggregate state or a projection to do validations?

More precisely, should my "write API" depend on a "read API" (a projection in Mongo for example) to validate constraint like "is there any room left", in the case I want to prevent over booking?

I guess it is different for a specific room (I could use the aggregate state) versus a pool of rooms (would need to validate against a projection)? But maybe I got it wrong.

Thank you!

**Comment by alexeyzimarev** [comment]
You can use whatever fits your use case. As soon as you get the information you need to make a decision, you're good. The aggregate state is always fully consistent, the read model state might be stale (which is controllable using the checkpoint position), so you make the choice based on those constraints I mentioned before.
